---
- name: Add Grafana's official APT key
  apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: Add Grafana's APT repository
  apt_repository:
    repo: "deb https://apt.grafana.com/ stable main"
    state: present

- name: Install Grafana Alloy
  apt:
    name: alloy
    state: present
    update_cache: yes

- name: Setup Alloy systemd drop-in to run as root
  file:
    path: /etc/systemd/system/alloy.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create override.conf for root execution
  copy:
    dest: /etc/systemd/system/alloy.service.d/override.conf
    content: |
      [Service]
      User=root
      Group=root
      EnvironmentFile=/etc/default/alloy.env
    owner: root
    group: root
    mode: '0644'
  notify: reload systemd

- name: Reload systemd to apply Alloy override
  systemd:
    daemon_reload: yes

- name: Create Alloy environment file
  copy:
    dest: /etc/default/alloy.env
    content: |
      ALLOY_DATASOURCE_USER="{{ ALLOY_DATASOURCE_USER }}"
      ALLOY_DATASOURCE_PASSWORD="{{ ALLOY_DATASOURCE_PASSWORD }}"
      MIMIR_URL="{{ MIMIR_URL }}"
      LOKI_URL="{{ LOKI_URL }}"
      TEMPO_URL="{{ TEMPO_URL }}"
    owner: root
    group: root
    mode: '0600'
  notify: restart alloy

- name: Change default config file path to a directory in /etc/default/alloy
  lineinfile:
    path: /etc/default/alloy
    regexp: '^CONFIG_FILE='
    line: 'CONFIG_FILE="/etc/alloy/config"'

- name: Ensure /etc/alloy/config directory exists
  file:
    path: /etc/alloy/config
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy Alloy configs to remote host
  copy:
    src: "{{ playbook_dir }}/config/alloy/{{ alloy_env | default('development') }}/"
    dest: /etc/alloy/config/
    owner: root
    group: root
    mode: '0644'
  notify: restart alloy

- name: Ensure Alloy is started and enabled
  systemd:
    name: alloy
    state: started
    enabled: yes
