- name: Install PostgreSQL
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
    state: present
    update_cache: yes
    cache_valid_time: 3600
  register: apt_res
  until: apt_res is success
  retries: 5
  delay: 10

- name: Start PostgreSQL service
  systemd:
    name: postgresql.service
    state: started
    enabled: yes

- name: Verify PostgreSQL version
  command: sudo -u postgres psql -c "SELECT version();"
  register: pg_version
  changed_when: false

- name: Show PostgreSQL version
  debug:
    var: pg_version.stdout_lines