- name: Copy Nginx main configuration file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: '0644'
    owner: root
    group: root
  notify: reload nginx

- name: Copy mime.types file
  copy:
    src: mime.types
    dest: /etc/nginx/mime.types
    mode: '0644'
    owner: root
    group: root
  notify: reload nginx

- name: Check if host-specific site configuration exists
  delegate_to: localhost
  stat:
    path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/nginx/default"
  register: host_site_config

- name: Copy host-specific site configuration
  copy:
    src: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/nginx/default"
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: '0644'
  when: host_site_config.stat.exists
  notify: reload nginx

- name: Enable site configuration
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  when: host_site_config.stat.exists
  notify: reload nginx
