- name: Install git
  apt:
    name: git
    state: present

- name: Create project directory
  file:
    path: /opt/openinfraquote
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Clone OpenInfraQuote repository
  git:
    repo: "https://github.com/terrateamio/openinfraquote.git"
    dest: /opt/openinfraquote
    force: yes
