all:
  children:
    app_servers:
      hosts:
        stag-app:
          ansible_host: host.docker.internal
          ansible_port: 2224
    db_servers:
      hosts:
        stag-db:
          ansible_host: host.docker.internal
          ansible_port: 2225
