- import_playbook: setup-base.yml
- import_playbook: setup-docker.yml
- import_playbook: setup-postgres.yml
- import_playbook: setup-mysql.yml
- import_playbook: setup-alloy.yml
- import_playbook: setup-nginx.yml
- import_playbook: setup-app.yml
- import_playbook: setup-observability.yml
- import_playbook: setup-semaphore.yml