- name: Setup Postgres
  hosts: all
  become: yes
  roles:
    - role: postgres_install
      when: database_server | default('') == 'postgres'
    - role: postgres_config
      when: database_server | default('') == 'postgres'
  vars:
    database_server: postgres

