all:
  children:
    app_servers:
      hosts:
        mir-app:
          ansible_host: host.docker.internal
          ansible_port: 2228
    db_servers:
      hosts:
        mir-db:
          ansible_host: host.docker.internal
          ansible_port: 2229
