all:
  children:
    control_nodes:
      hosts:
        control-production:
          ansible_host: 10.11.1.191
          ansible_port: 22
    app_servers:
      hosts:
        prod-app:
          ansible_host: 10.21.1.71
          ansible_port: 22
    db_servers:
      hosts:
        prod-db:
          ansible_host: 10.31.1.201
          ansible_port: 22
