all:
  children:
    control_nodes:
      hosts:
        control-production:
          ansible_host: host.docker.internal
          ansible_port: 2221
    app_servers:
      hosts:
        prod-app:
          ansible_host: host.docker.internal
          ansible_port: 2226
    db_servers:
      hosts:
        prod-db:
          ansible_host: host.docker.internal
          ansible_port: 2227
