all:
  children:
    app_servers:
      hosts:
        dev-app:
          ansible_host: host.docker.internal
          ansible_port: 2222
    db_servers:
      hosts:
        dev-db:
          ansible_host: host.docker.internal
          ansible_port: 2223
