timezone: "Asia/Jakarta"

# SSH Key Configuration
# Note: Run playbooks/common/extract-ssh-key.yml before other playbooks to extract keys to this path
ansible_ssh_private_key_file: "/tmp/ssh_key_{{ inventory_hostname }}.pem"

# Domain Configuration
domain_name: "kavanix.com"
certbot_admin_email: "eam24maret@gmail.com"

# Alloy Configuration
MIMIR_URL: "http://10.11.1.41:9009/api/v1/push"
LOKI_URL: "http://10.11.1.41:3100/loki/api/v1/push"
TEMPO_URL: "http://10.11.1.41:4319"
# PYROSCOPE_URL: "http://10.11.1.41:4040/ingest"