- name: Include setup tasks
  include_tasks: setup.yml
  tags: [setup]
  when: ansible_run_tags | length == 0 or 'setup' in ansible_run_tags

- name: Include restart tasks
  include_tasks: restart.yml
  tags: [restart]
  when: "'restart' in ansible_run_tags"

- name: Include backup tasks
  include_tasks: backup.yml
  tags: [backup]
  when: "'backup' in ansible_run_tags"
