- name: Start Alloy service
  systemd:
    name: alloy
    state: started
    enabled: yes
  tags: [start]
  when: ansible_run_tags | length == 0 or 'start' in ansible_run_tags

- name: Stop Alloy service
  systemd:
    name: alloy
    state: stopped
  tags: [stop]

- name: Restart Alloy service
  systemd:
    name: alloy
    state: restarted
  tags: [restart]

- name: Reload Alloy service
  systemd:
    name: alloy
    state: reloaded
  tags: [reload]
